"""Initial schema

Revision ID: ed57f237454a
Revises: 
Create Date: 2026-02-07 13:04:02.447825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed57f237454a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('nif', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_nif'), 'clients', ['nif'], unique=True)
    op.create_table('company',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('nif', sa.String(length=50), nullable=False),
    sa.Column('agent_commission_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_hash_algorithm', sa.String(length=20), nullable=False),
    sa.Column('file_hash_value', sa.String(length=128), nullable=False),
    sa.Column('email_message_id', sa.String(length=255), nullable=True),
    sa.Column('email_subject', sa.String(length=500), nullable=True),
    sa.Column('email_sender', sa.String(length=255), nullable=True),
    sa.Column('email_received_at', sa.DateTime(), nullable=True),
    sa.Column('document_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=True),
    sa.Column('error_type', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_occurred_at', sa.DateTime(), nullable=True),
    sa.Column('error_retryable', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('invoice_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash_algorithm', 'file_hash_value', name='uq_document_hash')
    )
    op.create_index('ix_documents_status', 'documents', ['status'], unique=False)
    op.create_table('providers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('nif', sa.String(length=50), nullable=False),
    sa.Column('provider_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_nif'), 'providers', ['nif'], unique=True)
    op.create_table('settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('anthropic_api_key', sa.String(length=255), nullable=False),
    sa.Column('outlook_configured', sa.Boolean(), nullable=False),
    sa.Column('outlook_refresh_token', sa.Text(), nullable=False),
    sa.Column('default_export_path', sa.String(length=500), nullable=False),
    sa.Column('extraction_prompt', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.Column('pol_code', sa.String(length=10), nullable=True),
    sa.Column('pol_name', sa.String(length=255), nullable=True),
    sa.Column('pod_code', sa.String(length=10), nullable=True),
    sa.Column('pod_name', sa.String(length=255), nullable=True),
    sa.Column('vessel', sa.String(length=255), nullable=True),
    sa.Column('containers', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('revenue_charges', sa.JSON(), nullable=False),
    sa.Column('cost_charges', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_bookings_client_id'), 'bookings', ['client_id'], unique=False)
    op.create_index('ix_bookings_status', 'bookings', ['status'], unique=False)
    op.create_index('ix_bookings_uuid', 'bookings', ['uuid'], unique=False)
    op.create_table('provider_invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('provider_type', sa.String(length=20), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('bl_references', sa.JSON(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_currency', sa.String(length=3), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_currency', sa.String(length=3), nullable=False),
    sa.Column('charges', sa.JSON(), nullable=False),
    sa.Column('source_document_id', sa.Uuid(), nullable=True),
    sa.Column('source_document_filename', sa.String(length=500), nullable=True),
    sa.Column('source_document_hash_algo', sa.String(length=20), nullable=True),
    sa.Column('source_document_hash_value', sa.String(length=128), nullable=True),
    sa.Column('extraction_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number', 'provider_id', name='uq_provider_invoice_number')
    )
    op.create_index('ix_provider_invoices_date', 'provider_invoices', ['invoice_date'], unique=False)
    op.create_index(op.f('ix_provider_invoices_provider_id'), 'provider_invoices', ['provider_id'], unique=False)
    op.create_table('client_invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('bl_reference', sa.String(length=100), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_currency', sa.String(length=3), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_currency', sa.String(length=3), nullable=False),
    sa.Column('charges', sa.JSON(), nullable=False),
    sa.Column('source_document_id', sa.Uuid(), nullable=True),
    sa.Column('source_document_filename', sa.String(length=500), nullable=True),
    sa.Column('source_document_hash_algo', sa.String(length=20), nullable=True),
    sa.Column('source_document_hash_value', sa.String(length=128), nullable=True),
    sa.Column('extraction_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['bl_reference'], ['bookings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number', 'client_id', name='uq_client_invoice_number')
    )
    op.create_index('ix_client_invoices_bl_reference', 'client_invoices', ['bl_reference'], unique=False)
    op.create_index(op.f('ix_client_invoices_client_id'), 'client_invoices', ['client_id'], unique=False)
    op.create_index('ix_client_invoices_date', 'client_invoices', ['invoice_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_client_invoices_date', table_name='client_invoices')
    op.drop_index(op.f('ix_client_invoices_client_id'), table_name='client_invoices')
    op.drop_index('ix_client_invoices_bl_reference', table_name='client_invoices')
    op.drop_table('client_invoices')
    op.drop_index(op.f('ix_provider_invoices_provider_id'), table_name='provider_invoices')
    op.drop_index('ix_provider_invoices_date', table_name='provider_invoices')
    op.drop_table('provider_invoices')
    op.drop_index('ix_bookings_uuid', table_name='bookings')
    op.drop_index('ix_bookings_status', table_name='bookings')
    op.drop_index(op.f('ix_bookings_client_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_providers_nif'), table_name='providers')
    op.drop_table('providers')
    op.drop_index('ix_documents_status', table_name='documents')
    op.drop_table('documents')
    op.drop_table('company')
    op.drop_index(op.f('ix_clients_nif'), table_name='clients')
    op.drop_table('clients')
    op.drop_table('agent')
    # ### end Alembic commands ###
